name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        env:
          RENDER_URL: ${{secrets.RENDER_URL}}
        run: |
          response=$(curl -Is "$RENDER_URL" | head -n 1)
          if echo "$response" | grep -q "HTTP/1.1 200"; then
            echo "Ping successful: $response"
          else
            echo "Ping failed: $response"
            exit 1
          fi
